{
 "title": "Servisos",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Erros 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  rate(\r\n    {app=\"servisos\", origin=\"http\"}\r\n      | json\r\n      | type=\"response\"\r\n      | status=\"500\"\r\n    [1m]\r\n  )\r\n) * 60"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  rate(\r\n    {app=\"servisos\", context=\"http\"} \r\n      | json \r\n      | type=\"request\" \r\n    [5m]\r\n  )\r\n) * 60"
    }
   ]
  },
  {
   "title": "Response time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({app=\"servisos\", context=\"http\"} | json | type=\"response\" | unwrap duration [$__auto])"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{context=\"database\"}"
    }
   ]
  },
  {
   "title": "Method Path Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10,\r\n    sum by (method, path) (\r\n  count_over_time(\r\n    {app=\"servisos\", context=\"http\"} \r\n      | json\r\n      | type=\"request\"\r\n      | path != \"\"\r\n    [$__interval]\r\n  ))\r\n)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (count_over_time({app=\"servisos\", context=\"http\"} | json | type=\"request\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs http",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"servisos\", context=\"http\"}"
    }
   ]
  },
  {
   "title": "Logs spring",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{context=\"spring\"}"
    }
   ]
  }
 ]
}